### ISSUE TITLE
[Bug] Getting View All instead of no response. 

### ISSUE THREAD

**Issue by Bugswriter** [Bugswriter/tuxi#103]
![image](https://user-images.githubusercontent.com/23283318/108494300-5bdcef00-72cd-11eb-962a-8a110fb80e72.png)

When I type `die noob korean`

I get view all.

See the bottom of this SS

![image](https://user-images.githubusercontent.com/23283318/108494369-757e3680-72cd-11eb-8140-e4200ef33101.png)

Why we are getting View All? This should be No result. 

PS : I am toxic gamer. I found lot of other country gamer. That's why I was translating die noob (in game)

**Comment by Genghius** [comment]
![image](https://user-images.githubusercontent.com/62076069/108500230-5e2c5280-72a7-11eb-94a3-ad3bf74142f4.png)
I am unable to replicate the problem.
However, i know what is causing the issue.
that is the newest change to the translate function.
someone made it faster by changing from what i originally wrote to this:
![image](https://user-images.githubusercontent.com/62076069/108500693-178b2800-72a8-11eb-860b-75a2644a53fe.png)

It is picking up any first child of any span
so it also picks up the first child of the span here:
![image](https://user-images.githubusercontent.com/62076069/108500465-b7948180-72a7-11eb-86ef-7c1ea9546117.png)
returning "View all".
The fix is quite simple, return the translate function to what I wrote originally (It still is quite slow so making it slower wont make much difference eh?).

**Comment by Genghius** [comment]
btw, we cant just use the class of the span used by the translate div in order to keep the current speed because:
![image](https://user-images.githubusercontent.com/62076069/108501113-b3b52f00-72a8-11eb-9048-14a0c12e32e9.png)
that span has no class.
So yes, our only options are to go back to what I had written.

**Comment by Genghius** [comment]
I fixed this with my PR panacea 3

**Comment by Genghius** [comment]
yikes, this has been fixed for a while now, can be closed.

**Comment by Bugswriter** [comment]
Oops .. I forget to close this one.
