### ISSUE TITLE
Weird strings of characters after installing

### ISSUE THREAD

**Issue by marcu123456** [Bugswriter/tuxi#170]
-  shell - zsh
- OS - MacOS Big Sur 11.2
- Terminal - Hyper.js
- location - /usr/local/bin/tuxi
- Query - is linux better than windows
- Dependencies installed via homebrew

**Steps to Reproduce the Problem**

Install dependencies via Brew
Copy Tuxi to path, make Tuxi excecutable.
Run Tuxi

**Expected Behavior**

Tuxi would return a short simple answer as seen in demonstration.

**Actual Behavior**

Tuxi responded with
sed: 1: ":a;N;$!ba;s/\n/ /g": unused label 'a;N;$!ba;s/\n/ /g'
sed: 1: ":a;N;$!ba;s/\n/ /g;s/nu ...": unused label 'a;N;$!ba;s/\n/ /g;s/null/\n/g'
usage: paste [-s] [-d delimiters] file ...

Linux is a family of open-source Unix-like operating systems based
on the Linux kernel, an operating system kernel first released
on September 17, 1991, by Linus Torvalds. Linux is typically
packaged in a Linux distribution.

**Comment by BeyondMagic** [comment]
That's due to the lack of MacOS support, make sure that you have GNU Core Utils installed in your computer and use tuxi from either of the following repositories:

- [Development Version](https://github.com/PureArtistry/tuxi/tree/purert-version) from #162
- [Main Version with MacOS support](https://github.com/Zhann/tuxi/tree/macos-compatibility) from #149

**Comment by marcu123456** [comment]
Thanks for your help.
