### ISSUE TITLE
The list's items are not being displayed for a particular search query

### ISSUE THREAD

**Issue by EPadronU** [Bugswriter/tuxi#89]
- `Bash`
- `EndeavourOS`:
- `Konsole 20.12.2`:
- `xterm-256color`

## Steps to Reproduce the Problem

Run Tuxi with this query string: `Need for Speed Heat cars list`

## Expected Behavior

Something along the lines of Google's instant answer:

```
THE FULL NFS HEAT CAR LIST
Acura NSX 2017 Sportscar.
Acura RSX-S 2004 Coupe.
Alfa Romeo Giulia Quadrofoglio 2016 Performance.
Aston Martin DB5 1964 Classic.
Aston Martin DB11 2017 Sportscar.
Aston Martin Vulcan 2016 Hypercar.
Audi R8 V10 Performance Coupe 2019 Supercar.
Audi S5 Sportback 2017 Performance.
```

## Actual Behavior

Only the _title_ of the list is displayed, even with the `-r` flag.

```
---
THE FULL NFS HEAT CAR LIST
---
```

**Comment by BeyondMagic** [comment]
`Rich answers` is with conflict again, it's query should be changed. I'll make an PR fixing this.

**Comment by Bugswriter** [comment]
wait. .don't do anything. I know what this is.

**Comment by Bugswriter** [comment]
I was writing about this bug right now creating a issue. 
Also congrats .. You FINALLY found this very obvious bug. I knew about it since I did my first commit.
It was really hard for me to add a fix for this. 
But lets see what our devs can do. I am closing this issue opening another issue.
@BeyondMagic I don't think this is fault in Rich answers ..this is actually a problem of how we are going to parse lists 
which don't have anything secondary.
We will get this issue with lists like this - 
![image](https://user-images.githubusercontent.com/23283318/108431419-d9badf00-7268-11eb-9682-1766e32d7de6.png)

Here below ubuntu there is no secondary text.

like this - 
![image](https://user-images.githubusercontent.com/23283318/108431463-e8a19180-7268-11eb-8154-9ea0395e7116.png)

**Comment by BeyondMagic** [comment]
@Bugswriter the current `Rich answers` is parsing only the title of element, if you change it to `di3YZe` it will give the list for #89.

**Comment by Bugswriter** [comment]
no just wait a sec. Let me open another issue. we will discuss this. I think there is some confusion. Regarding lists.

**Comment by BeyondMagic** [comment]
I understand, I'll wait.
